export function cx(...classes) {
  return classes.flat(Infinity).filter(Boolean).join(' ')
}

const ease = 'ease-[cubic-bezier(0.4,0,0.2,1)]'
const cardBase = `bg-[var(--card)] rounded-[var(--radius)] p-4 shadow-[var(--card-shadow)] border border-[var(--card-border)] transition-all duration-200 ${ease} hover:-translate-y-0.5 hover:shadow-[0_8px_24px_rgba(25,20,10,0.05)]`
const pillBase = 'inline-flex items-center justify-center gap-1 whitespace-nowrap rounded-full transition-all duration-150'
const inputBase = 'w-full rounded-[var(--radius-sm)] border-[1.5px] border-[var(--border)] bg-[var(--card)] px-4 py-3 text-[15px] text-[var(--text-primary)] outline-none transition-all duration-200 placeholder:text-[var(--text-muted)] focus:border-[var(--primary)] focus:shadow-[0_0_0_3px_rgba(13,148,136,0.12)]'
const buttonBase = `inline-flex w-full cursor-pointer items-center justify-center gap-2 rounded-[var(--radius-sm)] px-6 py-3 text-[15px] font-bold shadow-[0_2px_4px_rgba(25,20,10,0.02)] transition-all duration-200 ${ease} active:scale-[0.97]`

export const ui = {
  appShell: 'flex min-h-dvh w-full justify-center bg-transparent',
  appContainer: 'relative mx-auto flex min-h-dvh w-full max-w-[var(--max-width)] flex-col bg-[var(--bg)] shadow-[0_0_0_1px_rgba(25,20,10,0.03)]',
  screen: 'flex-1 overflow-y-auto pb-[var(--bottom-nav-height)]',

  header: 'sticky top-0 z-[100] flex h-[var(--header-height)] items-center justify-between gap-3 border-b border-[var(--border-light)] bg-white/90 px-4 shadow-[0_1px_3px_rgba(25,20,10,0.02)] backdrop-blur-md',
  headerDark: 'bg-[var(--navy)]',
  headerLogo: 'inline-block bg-gradient-to-br from-[var(--primary)] to-[#14B8A6] bg-clip-text text-[21px] font-extrabold tracking-[-0.6px] text-transparent',
  headerLogoAccent: 'bg-gradient-to-br from-[var(--navy)] to-[var(--navy-light)] bg-clip-text text-transparent',
  headerLocality: 'flex items-center gap-1 text-xs font-semibold text-[var(--text-secondary)]',
  headerActions: 'flex shrink-0 items-center gap-1.5',
  iconBtn: 'flex h-[38px] w-[38px] items-center justify-center rounded-full bg-[var(--bg)] text-lg text-[var(--text-primary)] transition-colors duration-150 hover:bg-[var(--border)]',

  bottomNav: 'fixed bottom-0 left-1/2 z-[200] flex h-[var(--bottom-nav-height)] w-full max-w-[var(--max-width)] -translate-x-1/2 items-center justify-around border-t border-[var(--border-light)] bg-white/90 px-2.5 shadow-[0_-4px_20px_rgba(25,20,10,0.03)] backdrop-blur-lg will-change-transform',
  navItem: 'flex min-h-[52px] flex-1 flex-col items-center justify-center gap-1 rounded-[var(--radius-sm)] px-0.5 py-1.5 text-[11px] font-semibold tracking-[0.1px] text-[var(--text-muted)] transition-all duration-200 ease-out active:scale-[0.92]',
  navItemActive: 'text-[var(--primary)]',
  navItemIcon: 'text-[21px] leading-none transition-transform duration-200',
  navItemIconActive: 'scale-110',
  navItemPost: `mt-[-12px] flex h-[52px] w-[52px] flex-none flex-col items-center justify-center gap-0 rounded-[18px] bg-gradient-to-br from-[var(--primary)] to-[#2DD4BF] text-2xl text-white shadow-[0_6px_16px_rgba(13,148,136,0.35)] transition-all duration-200 ${ease} hover:-translate-y-0.5 hover:scale-105 hover:shadow-[0_8px_20px_rgba(13,148,136,0.45)] active:translate-y-0 active:scale-95`,
  navItemPostIcon: 'block text-[30px] font-normal leading-none text-white',

  tabBar: 'flex gap-2 overflow-x-auto border-b border-[var(--border-light)] bg-[var(--card)] px-3.5 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
  tabBtn: `flex-none whitespace-nowrap border-b-[3px] border-transparent px-3 py-3.5 text-sm font-bold tracking-[0.1px] text-[var(--text-secondary)] transition-all duration-200 ${ease} active:scale-95`,
  tabBtnActive: 'border-[var(--primary)] text-[var(--primary)]',

  card: cardBase,
  cardList: 'flex flex-col gap-3 px-3.5 pb-5 pt-3',
  postCard: cx(cardBase, 'cursor-pointer'),
  postCardBoosted: 'border-[1.5px] border-amber-500',
  postCardHeader: 'mb-2.5 flex items-start gap-2.5',
  postAvatar: 'flex h-[38px] w-[38px] shrink-0 items-center justify-center rounded-full bg-[var(--primary-light)] text-sm font-bold text-[var(--primary)]',
  postMeta: 'min-w-0 flex-1',
  postName: 'text-[13px] font-bold leading-[1.2] text-[var(--text-primary)]',
  postSubMeta: 'mt-0.5 flex flex-wrap items-center gap-1.5',
  postLocality: 'flex items-center gap-0.5 text-[11px] text-[var(--text-secondary)]',
  postTime: 'text-[11px] text-[var(--text-muted)]',
  postDot: 'h-[3px] w-[3px] shrink-0 rounded-full bg-[var(--text-muted)]',
  postContent: 'mb-3 break-words text-[15px] leading-normal text-[var(--text-primary)]',
  postExpiry: 'mb-2.5 flex items-center gap-1 text-[11px] text-[var(--text-muted)]',
  postActions: 'flex flex-col items-stretch gap-2',
  postActionsPrimary: 'flex flex-wrap items-center gap-1.5',
  postActionsSecondary: 'flex w-full flex-wrap items-center justify-start gap-1.5 border-t border-[var(--border-light)] pt-1',

  actionBtn: cx(pillBase, 'border-[1.5px] border-[var(--border)] bg-transparent px-3 py-[7px] text-xs font-semibold text-[var(--text-secondary)] hover:bg-[var(--bg)]'),
  actionBtnActive: 'border-[var(--primary)] bg-[var(--primary-light)] text-[var(--primary)]',
  actionBtnHelp: 'border-[var(--success)] bg-[var(--success-light)] text-[var(--success)]',
  actionBtnCount: 'text-[11px]',
  actionIconBtn: cx(pillBase, 'min-h-8 flex-none border-[1.5px] border-[var(--border-light)] bg-transparent px-2.5 py-1.5 text-[11px] font-semibold tracking-[0.01em] text-[var(--text-muted)] hover:border-[var(--border)] hover:bg-[var(--bg)] hover:text-[var(--text-secondary)]'),
  actionIconBtnSaved: 'border-[var(--warning)] bg-[var(--warning-light)] font-bold text-[var(--warning)]',
  actionIconBtnReport: 'hover:border-[var(--error)] hover:bg-[#FFF5F5] hover:text-[var(--error)]',

  badge: 'inline-flex max-w-full shrink-0 items-center gap-1 rounded-full px-2 py-[3px] text-[11px] font-bold tracking-[0.02em]',
  badgeXs: 'px-1.5 py-0.5 text-[10px]',
  badgeIcon: 'text-xs leading-none normal-case',
  badgeLabel: 'truncate whitespace-nowrap text-[11px] uppercase tracking-[0.3px]',
  badgeLabelXs: 'text-[10px]',
  badgeInPostHeader: 'ml-auto self-start',

  providerCard: cardBase,
  providerHeader: 'mb-3 flex items-start gap-3',
  providerAvatar: 'flex h-12 w-12 shrink-0 items-center justify-center rounded-[14px] bg-[var(--primary-light)] text-lg font-extrabold text-[var(--primary)]',
  providerInfo: 'min-w-0 flex-1',
  providerName: 'text-[15px] font-bold leading-[1.2] text-[var(--text-primary)]',
  providerService: 'mt-0.5 text-[13px] font-semibold text-[var(--primary)]',
  providerLocality: 'mt-0.5 flex items-center gap-[3px] text-xs text-[var(--text-secondary)]',
  providerRecCount: 'mt-1.5 flex items-center gap-1 text-xs font-semibold text-[var(--success)]',
  providerNotes: 'mb-3 rounded-[var(--radius-sm)] bg-[var(--bg)] px-2.5 py-2',
  providerNote: 'text-xs leading-normal text-[var(--text-secondary)]',
  providerActions: 'flex gap-2',
  btnCall: 'flex flex-1 items-center justify-center gap-1.5 rounded-[var(--radius-sm)] border-[1.5px] border-[var(--success)] bg-[var(--success-light)] p-2.5 text-[13px] font-bold text-[var(--success)] transition-all duration-150',
  btnWhatsapp: 'flex flex-1 items-center justify-center gap-1.5 rounded-[var(--radius-sm)] border-[1.5px] border-[#128C7E] bg-[#DCF8C6] p-2.5 text-[13px] font-bold text-[#128C7E] transition-all duration-150',

  formGroup: 'mb-4',
  formGroupNoMargin: 'mb-0',
  formLabel: 'mb-1.5 block text-[13px] font-bold text-[var(--text-primary)]',
  formInput: inputBase,
  formInputReply: cx(inputBase, 'flex-1 rounded-full px-3 py-2 text-sm'),
  formTextarea: cx(inputBase, 'min-h-[110px] resize-none leading-normal'),
  formSelect: cx(inputBase, "appearance-none bg-[url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='8' viewBox='0 0 12 8'%3E%3Cpath fill='%23525866' d='M1 1l5 5 5-5'/%3E%3C/svg%3E\")] bg-[position:right_16px_center] bg-no-repeat pr-10"),
  charCount: 'mt-1 text-right text-[11px] text-[var(--text-muted)]',
  charCountOver: 'text-[var(--error)]',

  btn: buttonBase,
  btnAuto: cx(buttonBase, 'w-auto'),
  btnPrimary: 'bg-gradient-to-br from-[var(--primary)] to-[#2DD4BF] text-white hover:from-[var(--primary-dark)] hover:to-[var(--primary)] hover:shadow-[0_4px_12px_rgba(13,148,136,0.2)]',
  btnSecondary: 'border-[1.5px] border-[var(--border)] bg-[var(--card)] text-[var(--text-primary)] hover:border-[var(--text-secondary)] hover:bg-[var(--bg-alt)]',
  btnDisabled: 'cursor-not-allowed border-0 bg-[#ECEAE4] text-[var(--text-muted)] shadow-none hover:shadow-none active:scale-100',
  btnDanger: 'border-[1.5px] border-[var(--error)] bg-[var(--error-light)] text-[var(--error)] hover:bg-[var(--error)] hover:text-white',
  btnSm: 'px-4 py-2 text-[13px]',

  safetyBox: 'my-3 rounded-[var(--radius-sm)] border-[1.5px] border-amber-400 bg-[#FFF8F0] px-3.5 py-3',
  safetyBoxFlush: 'mt-0',
  safetyTitle: 'mb-1.5 flex items-center gap-1.5 text-xs font-extrabold uppercase tracking-[0.3px] text-amber-800',
  safetyList: 'flex list-disc flex-col gap-1 pl-4 text-xs leading-snug text-amber-900 marker:font-black marker:text-amber-500',

  overlay: 'fixed inset-0 z-[300] flex items-end justify-center bg-black/50',
  modal: 'max-h-[80vh] w-full max-w-[var(--max-width)] overflow-y-auto rounded-t-[var(--radius-lg)] bg-[var(--card)] px-5 pb-8 pt-5 motion-safe:animate-[slideUp_0.25s_ease-out]',
  modalHandle: 'mx-auto mb-4 h-1 w-9 rounded-sm bg-[var(--border)]',
  modalTitle: 'mb-4 text-[17px] font-extrabold text-[var(--text-primary)]',

  emptyState: 'flex flex-col items-center justify-center gap-3 px-8 py-[60px] text-center',
  emptyStateCompact: 'flex flex-col items-center justify-center gap-3 px-4 py-10 text-center',
  emptyIcon: 'select-none text-5xl leading-none opacity-85',
  emptyTitle: 'text-[17px] font-bold text-[var(--text-primary)]',
  emptySub: 'text-sm leading-normal text-[var(--text-secondary)]',

  sectionHeader: 'flex items-center justify-between px-4 pb-2 pt-3.5',
  sectionTitle: 'text-sm font-extrabold uppercase tracking-[0.4px] text-[var(--text-primary)]',
  sectionLink: 'text-[13px] font-semibold text-[var(--primary)]',

  // ── Login Screen ──────────────────────────────────────────
  loginShell: 'flex min-h-dvh w-full justify-center bg-[#F7F5F0] sm:items-center sm:p-6',
  loginContainer: 'relative mx-auto flex min-h-dvh w-full max-w-[430px] flex-col overflow-hidden bg-white sm:min-h-0 sm:rounded-[32px] sm:shadow-[0_24px_64px_rgba(25,20,10,0.12)] sm:ring-1 sm:ring-black/[0.04]',

  // Hero banner
  loginHero: 'relative flex shrink-0 flex-col overflow-hidden bg-gradient-to-br from-[#FF5C26] via-[#FF7540] to-[#FFA06E] px-7 pb-12 pt-12 text-white sm:px-8 sm:pt-16',
  loginHeroGlow: 'pointer-events-none absolute right-[-40px] top-[-40px] h-64 w-64 rounded-full bg-white/15 blur-[64px]',
  loginHeroGlowSecondary: 'pointer-events-none absolute bottom-[-30px] left-[-30px] h-56 w-56 rounded-full bg-[#FFE699]/20 blur-[48px]',
  loginHeroWave: 'pointer-events-none absolute inset-x-0 bottom-0 h-[32px] w-full',

  // Logo
  loginLogo: 'relative z-[1] text-[34px] font-black tracking-[-1.2px] text-white drop-shadow-sm flex items-center gap-2',
  loginLogoAccent: 'text-white/70',

  // Tagline
  loginTagline: 'relative z-[1] mt-4 max-w-[280px] text-[22px] font-extrabold leading-[1.3] text-white drop-shadow-sm',
  loginHeroDesc: 'relative z-[1] mt-2 max-w-[310px] text-[13.5px] leading-relaxed text-white/80',

  // Floating pills
  loginHeroPills: 'relative z-[1] mt-5 flex flex-wrap gap-2.5',
  loginHeroPill: 'rounded-full bg-white/15 px-3 py-1 text-[11px] font-bold text-white tracking-wide ring-1 ring-white/10 backdrop-blur-md',
  loginHeroBadge: 'relative z-[1] mt-5 inline-flex items-center gap-1.5 text-[11px] font-medium text-white/50',

  // Form card — floats above hero with big rounded top corners
  loginFormCard: 'relative z-10 -mt-6 flex flex-1 flex-col gap-6 rounded-t-[32px] bg-white px-7 pb-12 pt-8 shadow-[0_-8px_32px_rgba(25,20,10,0.06)] sm:px-8',

  // Form text
  loginTitle: 'text-[22px] font-extrabold tracking-[-0.5px] text-[var(--text-primary)]',
  loginSub: 'mt-1 text-[13.5px] leading-relaxed text-[var(--text-secondary)]',

  // Phone input — large, tactile, flag-prefixed
  loginPhoneWrap: 'flex items-stretch overflow-hidden rounded-[16px] border-2 border-[var(--border)] bg-[var(--bg-alt)] transition-all duration-200 focus-within:border-[var(--primary)] focus-within:bg-white focus-within:shadow-[0_0_0_4px_rgba(255,80,32,0.10)]',
  loginPhonePrefix: 'flex shrink-0 items-center gap-2 border-r-2 border-[var(--border)] bg-white/70 px-4 py-4 text-[15px] font-extrabold text-[var(--text-primary)]',
  loginPhoneInput: 'min-w-0 flex-1 border-0 bg-transparent px-4 py-4 text-[18px] font-semibold tracking-[0.05em] text-[var(--text-primary)] outline-none placeholder:font-normal placeholder:tracking-normal placeholder:text-[var(--text-muted)]',

  // Trust message
  loginTrust: 'flex items-center gap-2.5 rounded-[14px] border border-[var(--border-light)] bg-[var(--bg)] px-4 py-3 text-[12px] leading-relaxed text-[var(--text-muted)]',
  loginTrustIcon: 'shrink-0 text-base leading-none',

  loginToggle: 'p-2 text-center text-sm text-[var(--text-secondary)]',
  loginToggleButton: 'text-sm font-bold text-[var(--primary)]',
  divider: "my-1 flex items-center gap-3 text-xs text-[var(--text-muted)] before:h-px before:flex-1 before:bg-[var(--border)] before:content-[''] after:h-px after:flex-1 after:bg-[var(--border)] after:content-['']",
  demoLoginOptions: 'flex flex-col gap-2.5',
  demoUserBtn: `flex w-full items-center gap-3.5 rounded-[var(--radius-sm)] border-[1.5px] border-[var(--border)] bg-[var(--card)] px-[18px] py-3.5 text-left shadow-[0_2px_8px_rgba(25,20,10,0.02)] transition-all duration-200 ${ease} hover:border-[var(--primary)] hover:bg-[var(--primary-light)] hover:shadow-[0_4px_12px_rgba(0,104,94,0.08)] active:scale-[0.98]`,
  demoUserBtnCompact: 'px-3.5 py-3',
  demoUserAvatar: 'flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[var(--primary-light)] text-base font-extrabold text-[var(--primary)]',
  demoUserInfo: 'flex-1',
  demoUserName: 'text-sm font-bold text-[var(--text-primary)]',
  demoUserRole: 'mt-px text-xs text-[var(--text-secondary)]',

  categoryGrid: 'grid grid-cols-4 gap-2 px-3.5 py-3',
  categoryItem: `flex cursor-pointer flex-col items-center gap-2 rounded-[var(--radius-sm)] border-[1.5px] border-[var(--border)] bg-[var(--card)] px-2 py-3 transition-all duration-200 ${ease} hover:border-[var(--primary)] hover:bg-[var(--primary-light)] hover:shadow-[0_4px_12px_rgba(0,104,94,0.08)] active:scale-95`,
  categoryItemSelected: 'border-[var(--primary)] bg-[var(--primary-light)] shadow-[0_4px_12px_rgba(0,104,94,0.08)]',
  categoryIcon: 'text-2xl leading-none transition-transform duration-200',
  categoryIconSelected: 'scale-[1.15]',
  categoryLabel: 'text-center text-[11px] font-bold leading-[1.2] text-[var(--text-secondary)]',

  createTypeGrid: 'flex flex-col gap-2.5 p-4',
  createTypeCard: 'flex cursor-pointer items-center gap-4 rounded-[var(--radius)] border-2 border-[var(--border)] bg-[var(--card)] px-4 py-[18px] text-left transition-all duration-200 hover:border-[var(--primary)] hover:shadow-[var(--shadow)]',
  createTypeIcon: 'shrink-0 text-4xl',
  createTypeText: 'min-w-0',
  createTypeTitle: 'mb-[3px] text-base font-extrabold text-[var(--text-primary)]',
  createTypeDescription: 'text-xs leading-snug text-[var(--text-secondary)]',

  replyCard: 'flex gap-2.5 border-b border-[var(--border-light)] py-3',
  replyAvatar: 'flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[var(--bg)] text-xs font-bold text-[var(--text-secondary)]',
  replyContent: 'min-w-0 flex-1',
  replyMeta: 'mb-[3px] flex items-center gap-1.5',
  replyName: 'text-xs font-bold text-[var(--text-primary)]',
  replyTime: 'text-[11px] text-[var(--text-muted)]',
  replyText: 'text-[13px] leading-snug text-[var(--text-primary)]',
  replyTypeBadge: 'mb-1 inline-block rounded bg-[var(--success-light)] px-1.5 py-0.5 text-[10px] font-bold text-[var(--success)]',
  replyInputArea: 'sticky bottom-[var(--bottom-nav-height)] flex items-end gap-2 border-t border-[var(--border)] bg-[var(--card)] px-3.5 py-2.5',
  replyInputAreaFixed: 'fixed bottom-[var(--bottom-nav-height)] left-1/2 z-[150] flex w-full max-w-[var(--max-width)] -translate-x-1/2 items-end gap-2 border-t border-[var(--border)] bg-[var(--card)] px-3.5 py-2.5',
  replyQuickBtns: 'flex gap-1.5 overflow-x-auto px-3.5 pb-1 pt-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
  replyQuickBtnsFixed: 'fixed left-1/2 z-[150] flex w-full max-w-[var(--max-width)] -translate-x-1/2 gap-1.5 overflow-x-auto border-t border-[var(--border-light)] bg-[var(--bg)] px-3.5 pb-1 pt-2 [bottom:calc(var(--bottom-nav-height)+56px)] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
  quickReplyBtn: 'flex-none whitespace-nowrap rounded-full border-[1.5px] border-[var(--border)] bg-[var(--bg)] px-3 py-1.5 text-xs font-semibold text-[var(--text-secondary)] transition-all duration-150 hover:border-[var(--primary)] hover:bg-[var(--primary-light)] hover:text-[var(--primary)]',

  adminStats: 'grid grid-cols-2 gap-2.5 px-3.5 py-3',
  statCard: 'rounded-[var(--radius-sm)] border border-[var(--border-light)] bg-[var(--card)] p-3.5 shadow-[var(--shadow)]',
  statValue: 'mb-1 text-[28px] font-black leading-none text-[var(--primary)]',
  statLabel: 'text-xs font-medium text-[var(--text-secondary)]',
  flaggedCard: 'mx-3.5 mb-2.5 rounded-[var(--radius)] border-l-4 border-[var(--error)] bg-[var(--card)] px-4 py-3.5 shadow-[var(--shadow)]',
  flaggedHeader: 'mb-2 flex items-center justify-between',
  flaggedContent: 'mb-2.5 text-sm leading-snug text-[var(--text-primary)]',
  flaggedMeta: 'mb-2.5 text-xs text-[var(--text-muted)]',
  adminActions: 'flex flex-wrap gap-1.5',
  adminActionBtn: 'rounded-md border-[1.5px] px-3 py-1.5 text-xs font-bold transition-all duration-150',
  adminActionApprove: 'border-[var(--success)] bg-[var(--success-light)] text-[var(--success)]',
  adminActionRemove: 'border-[var(--error)] bg-[var(--error-light)] text-[var(--error)]',
  adminActionWarn: 'border-[var(--warning)] bg-[var(--warning-light)] text-[var(--warning)]',
  adminActionBan: 'border-[var(--navy)] bg-[var(--navy)] text-white',

  profileHero: 'relative flex flex-col items-center gap-2.5 bg-gradient-to-br from-[var(--navy)] via-[#1E2D5A] to-[#2D3A6B] px-5 pb-6 pt-7 text-white',
  profileAvatarLg: 'flex h-[72px] w-[72px] items-center justify-center rounded-[22px] border-[3px] border-white/25 bg-gradient-to-br from-[var(--primary)] to-[#14B8A6] text-[28px] font-extrabold text-white shadow-[0_4px_14px_rgba(13,148,136,0.3)]',
  profileName: 'text-xl font-extrabold',
  profileLocalityTag: 'flex items-center gap-1 text-[13px] text-white/70',
  profileStatsRow: 'mt-1 flex gap-6',
  profileStat: 'text-center',
  profileStatValue: 'text-xl font-black leading-none',
  profileStatLabel: 'mt-0.5 text-[11px] text-white/60',
  trustBadge: 'inline-flex items-center gap-1 rounded-full bg-white/15 px-2.5 py-1 text-xs font-bold',
  trustBadgeModerator: 'bg-[rgba(255,107,43,0.3)]',
  menuList: 'mx-3.5 my-3 overflow-hidden rounded-[var(--radius)] border border-[var(--border-light)] bg-[var(--card)] shadow-[var(--shadow)]',
  menuListFlush: 'm-0',
  menuItem: 'flex w-full cursor-pointer items-center gap-3.5 border-b border-[var(--border-light)] p-4 text-left transition-colors duration-150 last:border-b-0 hover:bg-[var(--bg)]',
  menuItemColumn: 'flex-col items-start gap-1.5',
  menuItemIcon: 'flex h-9 w-9 shrink-0 items-center justify-center rounded-[10px] bg-[var(--bg)] text-xl leading-none',
  menuItemText: 'flex-1',
  menuItemLabel: 'text-sm font-semibold text-[var(--text-primary)]',
  menuItemLabelDanger: 'text-[var(--error)]',
  menuItemSub: 'mt-px text-xs text-[var(--text-secondary)]',
  menuItemArrow: 'text-base text-[var(--text-muted)]',

  dividerLine: 'my-1 h-px bg-[var(--border-light)]',
  verifiedBadge: 'inline-flex items-center gap-[3px] rounded-full bg-[var(--primary-light)] px-[7px] py-0.5 text-[11px] font-bold text-[var(--primary)]',
  toast: 'pointer-events-none fixed left-1/2 z-[400] -translate-x-1/2 whitespace-nowrap rounded-3xl bg-[var(--navy)] px-[18px] py-2.5 text-[13px] font-semibold text-white shadow-[var(--shadow-lg)] motion-safe:animate-[toastIn_0.3s_ease-out] [bottom:calc(var(--bottom-nav-height)+12px)]',

  searchBar: 'border-b border-[var(--border)] bg-[var(--card)] px-3.5 py-2.5',
  searchInputWrap: 'flex items-center gap-2 rounded-xl border-[1.5px] border-[var(--border)] bg-[var(--bg)] px-3',
  searchInput: 'flex-1 bg-transparent py-2.5 text-sm text-[var(--text-primary)] outline-none',
  searchIcon: 'text-base text-[var(--text-muted)]',
  filterChips: 'flex gap-1.5 overflow-x-auto border-b border-[var(--border-light)] bg-[var(--card)] px-3.5 py-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
  filterChip: 'flex-none whitespace-nowrap rounded-full border-[1.5px] border-[var(--border)] bg-[var(--bg)] px-3 py-1.5 text-xs font-semibold text-[var(--text-secondary)] transition-all duration-150',
  filterChipActive: 'border-[var(--primary)] bg-[var(--primary)] text-white',

  spinner: 'mx-auto h-6 w-6 animate-spin rounded-full border-[3px] border-[var(--border)] border-t-[var(--primary)]',
  localityScreen: 'flex min-h-screen flex-col bg-[var(--card)]',
  localityHero: 'bg-gradient-to-br from-[var(--primary)] to-[#14B8A6] px-7 pb-8 pt-12 text-white',
  localityHeroTitle: 'mb-2 text-[26px] font-black',
  localityHeroDescription: 'text-sm leading-normal text-white/85',
  localityList: 'flex flex-1 flex-col gap-2 overflow-y-auto p-4',
  localityItem: 'flex cursor-pointer items-center justify-between rounded-[var(--radius-sm)] border-2 border-[var(--border)] bg-[var(--card)] p-4 transition-all duration-150 hover:border-[var(--primary)]',
  localityItemSelected: 'border-[var(--primary)] bg-[var(--primary-light)]',
  localityItemName: 'text-[15px] font-bold text-[var(--text-primary)]',
  localityItemSub: 'mt-0.5 text-xs text-[var(--text-secondary)]',
  tagFulfilled: 'inline-flex items-center gap-1 rounded-full bg-[var(--success-light)] px-2 py-[3px] text-[11px] font-bold text-[var(--success)]',
  tagExpired: 'inline-flex items-center gap-1 rounded-full bg-[var(--bg-alt)] px-2 py-[3px] text-[11px] font-bold text-[var(--text-muted)]',
}

export const badgeTone = {
  traffic: 'bg-[var(--cat-traffic-bg)] text-[var(--cat-traffic)]',
  transport: 'bg-[var(--cat-transport-bg)] text-[var(--cat-transport)]',
  police: 'bg-[var(--cat-police-bg)] text-[var(--cat-police)]',
  water: 'bg-[var(--cat-water-bg)] text-[var(--cat-water)]',
  power: 'bg-[var(--cat-power-bg)] text-[var(--cat-power)]',
  weather: 'bg-[var(--cat-weather-bg)] text-[var(--cat-weather)]',
  safety: 'bg-[var(--cat-safety-bg)] text-[var(--cat-safety)]',
  civic: 'bg-[var(--cat-civic-bg)] text-[var(--cat-civic)]',
  borrow: 'bg-[var(--cat-borrow-bg)] text-[var(--cat-borrow)]',
  rideshare: 'bg-[var(--cat-rideshare-bg)] text-[var(--cat-rideshare)]',
  urgent: 'bg-[var(--cat-urgent-bg)] text-[var(--cat-urgent)]',
  ticket: 'bg-[var(--cat-ticket-bg)] text-[var(--cat-ticket)]',
  errand: 'bg-[var(--cat-errand-bg)] text-[var(--cat-errand)]',
  medical: 'bg-red-100 text-red-700',
  need_to_buy: 'bg-[#FFF8F0] text-orange-700',
  need_to_purchase: 'bg-[#FFF8F0] text-orange-700',
  home_help: 'bg-[var(--success-light)] text-[var(--success)]',
  lost_found: 'bg-amber-100 text-amber-800',
  help: 'bg-[var(--success-light)] text-[var(--success)]',
  verified: 'bg-[var(--primary-light)] text-[var(--primary)]',
}
